# Generated by Django 4.0 on 2022-02-17 01:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a product category (Electronics, Style& Fashion, Sporting Goods, Pets Supplies, Other categories)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CountryOfOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the product's category (China, Canada, USA, Mexico, Haiti)", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=200)),
                ('expiry', models.CharField(max_length=30)),
                ('quantity', models.FloatField()),
                ('unit_cost', models.FloatField()),
                ('prize', models.CharField(max_length=30)),
                ('note', models.CharField(max_length=30)),
                ('addDate', models.DateField()),
                ('summary', models.TextField(help_text='Enter a brief description of the product', max_length=1000)),
                ('sku', models.CharField(help_text='13 Character<a href="https://www.shopify.ca/encyclopedia/stock-keeping-unit-sku">SKU number</a>', max_length=13, unique=True, verbose_name='SKU')),
                ('category', models.ManyToManyField(help_text='Select a category for this product', to='inventoryApp.Category')),
                ('countryoforigin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventoryApp.countryoforigin')),
            ],
            options={
                'ordering': ['itemName', 'supplier'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('business_type', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name', 'business_type'],
            },
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular product across whole organization', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('d', 'WIP'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='d', help_text='Product availability', max_length=1)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventoryApp.product')),
            ],
            options={
                'ordering': ['due_back'],
                'permissions': (('can_mark_returned', 'Set product as damaged'),),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventoryApp.supplier'),
        ),
    ]
